# Generated by Django 5.0 on 2024-02-21 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp of the most recent object edit', verbose_name='last edited at'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.CharField(blank=True, help_text='List of ingredients in the product', max_length=500, verbose_name='ingredients'),
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveSmallIntegerField(help_text='Size in grams')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'unique_together': {('product', 'size')},
            },
        ),
    ]
