# Generated by Django 5.0 on 2024-02-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_edited_at_product_ingredients_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sku',
            old_name='price',
            new_name='cost_price',
        ),
        migrations.AddField(
            model_name='sku',
            name='platform_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sku',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
