# Generated by Django 5.0 on 2024-02-21 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_price_sku_cost_price_sku_platform_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='measurement_unit',
            field=models.CharField(choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Milliliters'), ('L', 'Liters')], default='g', max_length=2),
        ),
        migrations.AddField(
            model_name='sku',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
        ),
        migrations.AlterField(
            model_name='sku',
            name='size',
            field=models.PositiveSmallIntegerField(help_text='Size', validators=[django.core.validators.MaxValueValidator(999)]),
        ),
    ]
